[build]
  command = "bin/bridgetown deploy && bin/netlify.sh"
  publish = "output"

[build.environment]
  NODE_ENV = "development"
  BRIDGETOWN_ENV = "production"
  RUBY_VERSION = "3.1.2"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=604800, s-max-age=604800"

[[headers]]
  for = "/"
  [headers.values]
    Link = [
      "<CSS_PATH>; rel=preload; as=style",
      "<JS_PATH>; rel=preload; as=script",
      "<https://NETLIFY_IMAGES_CDN_DOMAIN>; rel=preconnect"
    ]

[[headers]]
  for = "/*.(png|jpg|js|css|svg|woff|ttf|eot|ico|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-max-age=31536000"

[[redirects]]
  from = "/1927628/9957746-episode-1-andrew-mason"
  to = "/episodes/episode-1-andrew-mason"

[[redirects]]
  from = "/1927628/9958048-episode-2-jason-charnes"
  to = "/episodes/episode-2-jason-charnes"

[[redirects]]
  from = "/1927628/10073477-episode-3-nick-schwaderer"
  to = "/episodes/episode-3-nick-schwaderer"

[[redirects]]
  from = "/1927628/10458807-episode-4-brittany-martin"
  to = "/episodes/episode-4-brittany-martin"

[[redirects]]
  from = "/1927628/10542634-episode-5-sebastian-wilgosz"
  to = "/episodes/episode-5-sebastian-wilgosz"

[[redirects]]
  from = "/1927628/10596923-episode-6-kevin-murphy"
  to = "/episodes/episode-6-kevin-murphy"

[[redirects]]
  from = "/1927628/10597043-bonus-hockey-episode"
  to = "/episodes/bonus-hockey-episode"

[[redirects]]
  from = "/1927628/10746944-episode-7-chris-oliver"
  to = "/episodes/episode-7-chris-oliver"

[[redirects]]
  from = "/1927628"
  to = "/"

